const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium, expect } = require('@playwright/test');
const { createServer } = require('../serve.cjs');

test('showcase images, collections, wishlist, visit note, keyboard and mobile navigation', { timeout: 90000 }, async () => {
  const server = createServer();
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ headless: true, ...(process.platform === 'win32' ? { channel: 'msedge' } : {}) });
  const output = path.resolve(__dirname, '../../test-results'); fs.mkdirSync(output, { recursive: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(base);
    await expect(page.getByRole('heading', { level: 1 })).toContainText('Wear the moment.');
    await expect(page.locator('.hero-image img')).toBeVisible();
    await page.evaluate(async () => { await document.fonts.ready; await Promise.all([...document.querySelectorAll('main img')].map(img => { img.loading = 'eager'; return img.decode(); })); });
    assert.ok(await page.locator('main img').evaluateAll(images => images.every(img => img.complete && img.naturalWidth > 0)));
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.join(output, 'showcase-desktop.png'), fullPage: false });
    await page.getByRole('button', { name: 'For him', exact: true }).click();
    await expect(page.locator('.collection-card:visible')).toHaveCount(1);
    await expect(page.locator('.collection-card:visible')).toHaveAttribute('data-category', 'groom');
    await page.getByRole('button', { name: 'All collections', exact: false }).click();
    await expect(page.locator('.collection-card:visible')).toHaveCount(3);
    await page.getByRole('button', { name: 'Save The Bridal Edit', exact: true }).click();
    await page.reload();
    await expect(page.locator('#saved-count')).toHaveText('1');
    await page.getByRole('button', { name: 'View saved collections (1)', exact: true }).click();
    await expect(page.getByRole('dialog', { name: 'Saved collections' })).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.locator('#wishlist-dialog')).not.toBeVisible();
    await page.getByRole('button', { name: 'Explore The Bridal Edit', exact: true }).click();
    await expect(page.getByRole('dialog', { name: 'The Bridal Edit' })).toBeVisible();
    await page.getByRole('button', { name: 'Include in my visit plan', exact: false }).click();
    await expect(page.locator('#collection-dialog')).not.toBeVisible();
    await page.getByLabel('Your name').fill('Showcase visitor');
    await page.getByLabel('Occasion', { exact: true }).selectOption('Wedding');
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Save my styling note', exact: false }).click();
    const download = await downloadPromise;
    assert.equal(download.suggestedFilename(), 'my-wabi-sabi-styling-note.txt');
    const content = fs.readFileSync(await download.path(), 'utf8');
    assert.match(content, /Showcase visitor/); assert.match(content, /The Bridal Edit/);
    await expect(page.locator('#form-status')).toContainText('No booking has been made');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.getByRole('button', { name: 'Open navigation', exact: true }).click();
    await expect(page.locator('#mobile-menu')).toBeVisible();
    await page.locator('#mobile-menu').getByRole('link', { name: 'The collection', exact: true }).click();
    await expect(page.locator('#mobile-menu')).not.toBeVisible();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.screenshot({ path: path.join(output, 'showcase-mobile.png'), fullPage: false });
    await page.locator('#collections').screenshot({ path: path.join(output, 'showcase-collections.png') });
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
});
